//*****************************************************************************
//
// enet_io.c - I/O control via a web server.
//
// Copyright (c) 2013-2016 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
// Texas Instruments (TI) is supplying this software for use solely and
// exclusively on TI's microcontroller products. The software is owned by
// TI and/or its suppliers, and is protected under applicable copyright
// laws. You may not combine this software with "viral" open-source
// software in order to form a larger program.
// 
// THIS SOFTWARE IS PROVIDED "AS IS" AND WITH ALL FAULTS.
// NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT
// NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE. TI SHALL NOT, UNDER ANY
// CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
// DAMAGES, FOR ANY REASON WHATSOEVER.
// 
// This is part of revision 2.1.3.156 of the EK-TM4C1294XL Firmware Package.
//
//*****************************************************************************

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

/* hw headers */
#include "inc/hw_ints.h"
#include "inc/hw_memmap.h"
#include "inc/hw_nvic.h"
#include "inc/hw_types.h"
#include "drivers/pinout.h"
#include "drivers/buttons.h"


/* Peripherial drivers */
#include "driverlib/debug.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/pin_map.h"
#include "driverlib/rom.h"
#include "driverlib/rom_map.h"
#include "driverlib/sysctl.h"
#include "driverlib/flash.h"
#include "driverlib/sysctl.h"
#include "driverlib/uart.h"
#include "driverlib/systick.h"
#include "driverlib/timer.h"

/* Utils */
#include "utils/uartstdio.h"
#include "utils/locator.h"
#include "utils/lwiplib.h"
#include "utils/ustdlib.h"
#include "utils/locator.h"
#include "utils/lwiplib.h"
#include "utils/uartstdio.h"
#include "utils/ustdlib.h"

/* misc */
#include "httpserver_raw/httpd.h"
#include "io.h"
#include "cgifuncs.h"

/* sensor libraries */
/* I2C driver lib */
#include "sensorlib/i2cm_drv.h"

/* TMP006 - temperature */
#include "sensorlib/hw_tmp006.h"
#include "sensorlib/tmp006.h"

/* SHT21 - humidity */
#include "sensorlib/sht21.h"
#include "sensorlib/hw_sht21.h"

/* BMP180 - pressure */
#include "sensorlib/hw_bmp180.h"
#include "sensorlib/bmp180.h"

/* ISL29023 - light */
#include "sensorlib/isl29023.h"
#include "sensorlib/hw_isl29023.h"

//*****************************************************************************
//
//! \addtogroup example_list
//! <h1>Ethernet-based I/O Control (enet_io)</h1>
//!
//! This example application demonstrates web-based I/O control using the
//! Tiva Ethernet controller and the lwIP TCP/IP Stack.  DHCP is used to
//! obtain an Ethernet address.  If DHCP times out without obtaining an
//! address, a static IP address will be chosen using AutoIP.  The address that
//! is selected will be shown on the UART allowing you to access the
//! internal web pages served by the application via your normal web browser.
//!
//! Two different methods of controlling board peripherals via web pages are
//! illustrated via pages labeled ``IO Control Demo 1'' and ``IO Control
//! Demo 2'' in the navigation menu on the left of the application's home page.
//! In both cases, the example allows you to toggle the state of the user LED
//! on the board and set the speed of a blinking LED.
//!
//! ``IO Control Demo 1'' uses JavaScript running in the web browser to send
//! HTTP requests for particular special URLs.  These special URLs are
//! intercepted in the file system support layer (io_fs.c) and used to
//! control the LED and animation LED.  Responses generated by the board are
//! returned to the browser and inserted into the page HTML dynamically by
//! more JavaScript code.
//!
//! ``IO Control Demo 2'' uses standard HTML forms to pass parameters to CGI
//! (Common Gateway Interface) handlers running on the board.  These handlers
//! process the form data and control the animation and LED as requested before
//! sending a response page (in this case, the original form) back to the
//! browser.  The application registers the names and handlers for each of its
//! CGIs with the HTTPD server during initialization and the server calls
//! these handlers after parsing URL parameters each time one of the CGI URLs
//! is requested.
//!
//! Information on the state of the various controls in the second demo is
//! inserted into the served HTML using SSI (Server Side Include) tags which
//! are parsed by the HTTPD server in the application.  As with the CGI
//! handlers, the application registers its list of SSI tags and a handler
//! function with the web server during initialization and this handler is
//! called whenever any registered tag is found in a .shtml, .ssi, .shtm or
//! .xml file being served to the browser.
//!
//! In addition to LED and animation speed control, the second example also
//! allows a line of text to be sent to the board for output to the UART.
//! This is included to illustrate the decoding of HTTP text strings.
//!
//! Note that the web server used by this example has been modified from the
//! example shipped with the basic lwIP package.  Additions include SSI and
//! CGI support along with the ability to have the server automatically insert
//! the HTTP headers rather than having these built in to the files in the
//! file system image.
//!
//! Source files for the internal file system image can be found in the ``fs''
//! directory.  If any of these files are changed, the file system image
//! (io_fsdata.h) should be rebuilt by running the following command from the
//! enet_io directory:
//!
//! ../../../../tools/bin/makefsfile -i fs -o io_fsdata.h -r -h -q
//!
//! For additional details on lwIP, refer to the lwIP web page at:
//! http://savannah.nongnu.org/projects/lwip/
//
//*****************************************************************************

//*****************************************************************************
//
// Defines for setting up the system clock.
//
//*****************************************************************************
#define SYSTICKHZ               100
#define SYSTICKMS               (1000 / SYSTICKHZ)

//*****************************************************************************
//
// Interrupt priority definitions.  The top 3 bits of these values are
// significant with lower values indicating higher priority interrupts.
//
//*****************************************************************************
#define SYSTICK_INT_PRIORITY    0x80		/* Systick INT priority is the highest */
#define ETHERNET_INT_PRIORITY   0xC0		/* ETH priority */
#define GPIOH_INT_PRIORITY		0xE0		/* Light threshold INT priority is the lowest */
#define WS_REFRESH_PERIOD_MS	1000			/* Refreshing period of sensor data */
//*****************************************************************************
/*  Define sensor addresses */
//*****************************************************************************
#define TMP006_I2C_ADDRESS      0x41
#define SHT21_I2C_ADDRESS  		0x40
#define BMP180_I2C_ADDRESS      0x77
#define ISL29023_I2C_ADDRESS    0x44

//*****************************************************************************
//
// Global instance structure for the I2C master driver and sensors.
//
//*****************************************************************************
tI2CMInstance I2Cinstance;
tTMP006 TempInst;
tSHT21 HumidityInst;
tBMP180 PressureInst;
tISL29023 LightInst;

//*****************************************************************************
//
// Global new data flag to alert main that sensor data is ready and
// flag to store the error condition if encountered for each sensor.
//
//*****************************************************************************
// TMP 006
bool TempDataFlag;					/* Temperature measurement is ready */
volatile uint_fast8_t TempStatus;			/* Status of TMP006 sensor, used to indicate errors */
volatile bool TempMeasReady;				/* TMP006 sensor's DRDY interrupt sets this flag, if measurement is ready */

//SHT21
bool HumidityDataFlag;				/* Humidity measurement is ready */
volatile uint_fast8_t HumidityStatus;		/* Status of TMP006 sensor, used to indicate errors */

//BMP180
bool PressureDataFlag;				/* Pressure measurement is ready */
volatile uint_fast8_t PressureStatus;		/* Status of TMP006 sensor, used to indicate errors */

//ISL29023
bool LightDataFlag;				/* Light measurement is ready */
volatile uint_fast8_t LightStatus;			/* Status of TMP006 sensor, used to indicate errors */
volatile bool LightIntensityFlag;			/* Intensity flag is used for indicating the application, if intensity
											 * is out of threshold */

//I2C
bool I2COperationInProgress;
int SystickCounter = 0;

const float LightThresholdHigh[4] =
{
    810.0f, 3240.0f, 12960.0f, 64000.0f
};
const float LightThresholdLow[4] =
{
    0.0f, 760.0f, 3040.0f, 12160.0f
};

/* Measured data */
float TempAmbientMeas, TempObjectMeas;
float HumidityMeas;
float PressureMeas;
float LightMeas;

/* Wheater Station application sensor type for distinguishing sensors in application */
typedef enum {
	WS_TemperatureSensor 	= 0x01u,
	WS_HumiditySensor		= 0x02u,
	WS_PressureSensor		= 0x03u,
	WS_LightSensor			= 0x04u
}WS_Sensor_t;

//*****************************************************************************
//
// A set of flags.  The flag bits are defined as follows:
//
//     0 -> An indicator that the animation timer interrupt has occurred.
//
//*****************************************************************************
#define FLAG_TICK            0
static volatile unsigned long g_ulFlags;
static volatile bool ipSetupRdy;

//*****************************************************************************
//
// External Application references.
//
//*****************************************************************************
extern void httpd_init(void);

//*****************************************************************************
//
// SSI tag indices for each entry in the g_pcSSITags array.
//
//*****************************************************************************
#define SSI_INDEX_LEDSTATE  0
#define SSI_INDEX_FORMVARS  1
#define SSI_INDEX_SPEED     2

//*****************************************************************************
//
// This array holds all the strings that are to be recognized as SSI tag
// names by the HTTPD server.  The server will call SSIHandler to request a
// replacement string whenever the pattern <!--#tagname--> (where tagname
// appears in the following array) is found in ".ssi", ".shtml" or ".shtm"
// files that it serves.
//
//*****************************************************************************
static const char *g_pcConfigSSITags[] =
{
    "LEDtxt",        // SSI_INDEX_LEDSTATE
    "FormVars",      // SSI_INDEX_FORMVARS
    "speed"          // SSI_INDEX_SPEED
};

//*****************************************************************************
//
// The number of individual SSI tags that the HTTPD server can expect to
// find in our configuration pages.
//
//*****************************************************************************
#define NUM_CONFIG_SSI_TAGS     (sizeof(g_pcConfigSSITags) / sizeof (char *))

//*****************************************************************************
//
// Prototypes for the various CGI handler functions.
//
//*****************************************************************************
static char *ControlCGIHandler(int32_t iIndex, int32_t i32NumParams,
                               char *pcParam[], char *pcValue[]);
static char *SetTextCGIHandler(int32_t iIndex, int32_t i32NumParams,
                               char *pcParam[], char *pcValue[]);

//*****************************************************************************
//
// Prototype for the main handler used to process server-side-includes for the
// application's web-based configuration screens.
//
//*****************************************************************************
static int32_t SSIHandler(int32_t iIndex, char *pcInsert, int32_t iInsertLen);

//*****************************************************************************
//
// CGI URI indices for each entry in the g_psConfigCGIURIs array.
//
//*****************************************************************************
#define CGI_INDEX_CONTROL       0
#define CGI_INDEX_TEXT          1

//*****************************************************************************
//
// This array is passed to the HTTPD server to inform it of special URIs
// that are treated as common gateway interface (CGI) scripts.  Each URI name
// is defined along with a pointer to the function which is to be called to
// process it.
//
//*****************************************************************************
static const tCGI g_psConfigCGIURIs[] =
{
    { "/iocontrol.cgi", (tCGIHandler)ControlCGIHandler }, // CGI_INDEX_CONTROL
    { "/settxt.cgi", (tCGIHandler)SetTextCGIHandler }     // CGI_INDEX_TEXT
};

//*****************************************************************************
//
// The number of individual CGI URIs that are configured for this system.
//
//*****************************************************************************
#define NUM_CONFIG_CGI_URIS     (sizeof(g_psConfigCGIURIs) / sizeof(tCGI))

//*****************************************************************************
//
// The file sent back to the browser by default following completion of any
// of our CGI handlers.  Each individual handler returns the URI of the page
// to load in response to it being called.
//
//*****************************************************************************
#define DEFAULT_CGI_RESPONSE    "/io_cgi.ssi"

//*****************************************************************************
//
// The file sent back to the browser in cases where a parameter error is
// detected by one of the CGI handlers.  This should only happen if someone
// tries to access the CGI directly via the broswer command line and doesn't
// enter all the required parameters alongside the URI.
//
//*****************************************************************************
#define PARAM_ERROR_RESPONSE    "/perror.htm"

#define JAVASCRIPT_HEADER                                                     \
    "<script type='text/javascript' language='JavaScript'><!--\n"
#define JAVASCRIPT_FOOTER                                                     \
    "//--></script>\n"

//*****************************************************************************
//
// Timeout for DHCP address request (in seconds).
//
//*****************************************************************************
#ifndef DHCP_EXPIRE_TIMER_SECS
#define DHCP_EXPIRE_TIMER_SECS  45
#endif

//*****************************************************************************
//
// The current IP address.
//
//*****************************************************************************
uint32_t g_ui32IPAddress;

//*****************************************************************************
//
// The system clock frequency.  Used by the SD card driver.
//
//*****************************************************************************
uint32_t g_ui32SysClock;
int32_t tempInteger, tempFraction;
int32_t humidityInteger, humidityFraction;
int32_t pressureInteger, pressureFraction;
int32_t lightInteger, lightFraction;


//*****************************************************************************
//
// The error routine that is called if the driver library encounters an error.
//
//*****************************************************************************
#ifdef DEBUG
void
__error__(char *pcFilename, uint32_t ui32Line)
{
}
#endif


/*****************************************************************************
* Sensor callback functions.  Called at the end of each sensor's driver
* transactions. These are called from I2C interrupt context. Therefore, we just
* set a flag and let main do the bulk of the computations and display.
*******************************************************************************/

/* Callback to call after temperature measuremenet */
void TemperatureAppCallback(void *pvCallbackData, uint_fast8_t ui8Status)
{
	/* If the transaction succeeded set the data flag to indicate to
	 * application that this transaction is complete and data may be ready. */
    if(ui8Status == I2CM_STATUS_SUCCESS)
    {
        TempDataFlag = true;
    }

    /* Store the most recent status in case it was an error condition. */
    TempStatus = ui8Status;

    /* I2C operation is over */
    I2COperationInProgress = false;
}

/* Callback to call after humidity measurement */
void HumidityAppCallback(void * pvCallbackData, uint_fast8_t ui8Status)
{
    /* If the transaction succeeded set the data flag to indicate to
     * application that this transaction is complete and data may be ready. */
    if(ui8Status == I2CM_STATUS_SUCCESS)
    {
        HumidityDataFlag = true;
    }

    /* Store the most recent status in case it was an error condition. */
    HumidityStatus = ui8Status;

    /* I2C operation is over */
    I2COperationInProgress = false;
}

/* Callback to call after pressure measurement */
void PressureAppCallback(void* pvCallbackData, uint_fast8_t ui8Status)
{
    /* If the transaction was successful then set the data ready flag. */
    if(ui8Status == I2CM_STATUS_SUCCESS)
    {
        PressureDataFlag = true;
    }

    /* Store the most recent status in case it was an error condition. */
    PressureStatus = ui8Status;

    /* I2C operation is over */
    I2COperationInProgress = false;
}

void LightAppCallback(void *pvCallbackData, uint_fast8_t ui8Status)
{
	/* If the transaction was successful then set the data ready flag. */
    if(ui8Status == I2CM_STATUS_SUCCESS)
    {
        LightDataFlag = true;
    }

    /* Store the most recent status in case it was an error condition. */
    LightStatus = ui8Status;

    /* I2C operation is over */
    I2COperationInProgress = false;
}

void DefaultAppCallback(void *pvCallbackData, uint_fast8_t ui8Status)
{
	/* I2C operation is over */
	I2COperationInProgress = false;

}
/****************************************************************************
 *
 * Sensor application error handler function.
 *
 *****************************************************************************/
/* Error handler for temperature sensor */
void UniversalAppErrorHandler(char *pcFilename, uint_fast32_t ui32Line, WS_Sensor_t sensor)
{
	/* Send error meassage according to the type of sensor */
	switch(sensor)
	{
		case WS_TemperatureSensor:
		    UARTprintf("Error in temperature sensor, error code:%d\n File: %s, Line: %d\n",
		                TempStatus, pcFilename, ui32Line);
		break;
		case WS_HumiditySensor:
			UARTprintf("Error in humidity sensor, error code:%d\n File: %s, Line: %d\n",
					    HumidityStatus, pcFilename, ui32Line);
		break;
		case WS_PressureSensor:
			UARTprintf("Error in pressure sensor, error code:%d\n File: %s, Line: %d\n",
					    PressureStatus, pcFilename, ui32Line);
		break;
		case WS_LightSensor:
			UARTprintf("Error in light sensor, error code:%d\n File: %s, Line: %d\n",
					    LightStatus, pcFilename, ui32Line);
		break;

	};
	/* Go to sleep wait for interventions. */
    while(1)
    {
        ROM_SysCtlSleep();
    }
}


/****************************************************************************
 *
 * I2C application wait function.
 *
 *****************************************************************************/
void I2CAppWait(char *pcFilename, uint_fast32_t ui32Line, WS_Sensor_t sensor)
{

	switch(sensor)
	{
		case WS_TemperatureSensor:
			while( I2COperationInProgress )
			{
				MAP_SysCtlSleep();
			}
			if(TempStatus)
			{
				UniversalAppErrorHandler(pcFilename, ui32Line, sensor);
			}
		break;
		case WS_HumiditySensor:
			while( I2COperationInProgress )
			{
				MAP_SysCtlSleep();
			}
			if(HumidityStatus)
			{
				UniversalAppErrorHandler(pcFilename, ui32Line, sensor);
			}
		break;
		case WS_PressureSensor:
			while( I2COperationInProgress )
			{
				MAP_SysCtlSleep();
			}
			if(PressureStatus)
			{
				UniversalAppErrorHandler(pcFilename, ui32Line, sensor);
			}
		case WS_LightSensor:
			while( I2COperationInProgress )
			{
				MAP_SysCtlSleep();
			}
			if(LightStatus)
			{
				UniversalAppErrorHandler(pcFilename, ui32Line, sensor);
			}

		break;
	};
}

/*****************************************************************************
 *
 * Called by the NVIC as a result of I2C Interrupt. I2C7 is the I2C connection
 * to the TMP006 for BoosterPack 1 interface.  I2C8 must be used for
 * BoosterPack 2 interface.  Must also move this function pointer in the
 * startup file interrupt vector table for your tool chain if using BoosterPack
 * 2 interface headers.
 *
******************************************************************************/
/* Handles the DRDY interrupt of TMP006 temperature sensor */
void TempIntHandler(void)
{
    uint32_t ui32Status;

    ui32Status = GPIOIntStatus(GPIO_PORTH_BASE, true);

    /* Clear all the pin interrupts that are set */
    GPIOIntClear(GPIO_PORTH_BASE, ui32Status);

    if(ui32Status & GPIO_PIN_2)
    {
        /* A conversion is complete and ready to be fetched, set flag to indicate it to the application */
        TempMeasReady = true;
    }
}

/*Handles the I2C interrupts */
void UniversalI2CIntHandler(void)
{

	/* I2CMIntHandler can receive the instance structure pointer as an argument. */
    I2CMIntHandler(&I2Cinstance);
}

/*****************************************************************************
 *
 *  GPIOPortE interrupt handler for light sensor indicating, that light level has crossed outside of
 * the intensity threshold levels set in INT_LT and INT_HT registers. It's a very low priority
 * interrupt, we want to get notification of light values outside our thresholds but it is not the
 *  most important thing.
 *
******************************************************************************/
void LightIntHandler(void)
{
	if(!LightIntensityFlag)
	{
		unsigned long ulStatus;

		ulStatus = GPIOIntStatus(GPIO_PORTE_BASE, true);

		/* Clear pin interrupts */
		GPIOIntClear(GPIO_PORTE_BASE, ulStatus);

		if(ulStatus & GPIO_PIN_5)
		{
			/* Light level has crossed outside of  the intensity threshold levels set in INT_LT and INT_HT
			 * set flag to indicate.*/
			LightIntensityFlag = 1;
		}

	}
}

int32_t IntegerPart(float Value)
{
	return ((int32_t) Value);
}

int32_t FractionPart(float Value)
{
	int32_t FractionPart = (int32_t) (Value * 1000.0f);
	FractionPart = FractionPart - (IntegerPart(Value) * 1000);
	if(FractionPart < 0)
	{
		FractionPart *= -1;
	}
	return FractionPart;
}

/*****************************************************************************
*
* Intensity and Range Tracking Function.  This adjusts the range and interrupt
* thresholds as needed.  Uses an 80/20 rule. If light is greater then 80% of
* maximum value in this range then go to next range up. If less than 20% of
* potential value in this range go the next range down.
*
*******************************************************************************/
void LightAppAdjustRange(tISL29023 *pInst)
{
    float Ambient;
    uint8_t NewRange;

    NewRange = LightInst.ui8Range;

    /* Get a local floating point copy of the latest light data */
    ISL29023DataLightVisibleGetFloat(&LightInst, &Ambient);

    /* Check if we crossed the upper threshold. */
    if(Ambient > LightThresholdHigh[LightInst.ui8Range])
    {
    	/* The current intensity is over our threshold so adjust the range accordingly */
        if(LightInst.ui8Range < ISL29023_CMD_II_RANGE_64K)
        {
            NewRange = LightInst.ui8Range + 1;
        }
    }

    /* Check if we crossed the lower threshold */
    if(Ambient < LightThresholdLow[LightInst.ui8Range])
    {
        /* If possible go to the next lower range setting and reconfigure the thresholds. */
        if(LightInst.ui8Range > ISL29023_CMD_II_RANGE_1K)
        {
            NewRange = LightInst.ui8Range - 1;
        }
    }

    /* If the desired range value changed then send the new range to the sensor */
    if(NewRange != LightInst.ui8Range)
    {
    	I2COperationInProgress = true;
        ISL29023ReadModifyWrite(&LightInst, ISL29023_O_CMD_II,
                                ~ISL29023_CMD_II_RANGE_M, NewRange,
                                DefaultAppCallback, &LightInst);

        /* Wait for transaction to complete */
        I2CAppWait(__FILE__, __LINE__, WS_LightSensor);
    }
}

//*****************************************************************************
//
// This CGI handler is called whenever the web browser requests iocontrol.cgi.
//
//*****************************************************************************
static char *
ControlCGIHandler(int32_t iIndex, int32_t i32NumParams, char *pcParam[],
                  char *pcValue[])
{
    int32_t i32LEDState, i32Speed;
    bool bParamError;

    //
    // We have not encountered any parameter errors yet.
    //
    bParamError = false;

    //
    // Get each of the expected parameters.
    //
    i32LEDState = FindCGIParameter("LEDOn", pcParam, i32NumParams);
    i32Speed = GetCGIParam("speed_percent", pcParam, pcValue, i32NumParams,
            &bParamError);

    //
    // Was there any error reported by the parameter parser?
    //
    if(bParamError || (i32Speed < 0) || (i32Speed > 100))
    {
        return(PARAM_ERROR_RESPONSE);
    }

    //
    // We got all the parameters and the values were within the expected ranges
    // so go ahead and make the changes.
    //
    io_set_led((i32LEDState == -1) ? false : true);
    io_set_animation_speed(i32Speed);

    //
    // Send back the default response page.
    //
    return(DEFAULT_CGI_RESPONSE);
}

//*****************************************************************************
//
// This CGI handler is called whenever the web browser requests settxt.cgi.
//
//*****************************************************************************
static char *
SetTextCGIHandler(int32_t i32Index, int32_t i32NumParams, char *pcParam[],
                  char *pcValue[])
{
    long lStringParam;
    char pcDecodedString[48];

    //
    // Find the parameter that has the string we need to display.
    //
    lStringParam = FindCGIParameter("DispText", pcParam, i32NumParams);

    //
    // If the parameter was not found, show the error page.
    //
    if(lStringParam == -1)
    {
        return(PARAM_ERROR_RESPONSE);
    }

    //
    // The parameter is present. We need to decode the text for display.
    //
    DecodeFormString(pcValue[lStringParam], pcDecodedString, 48);

    //
    // Print sting over the UART
    //
    UARTprintf(pcDecodedString);
    UARTprintf("\n");

    //
    // Tell the HTTPD server which file to send back to the client.
    //
    return(DEFAULT_CGI_RESPONSE);
}

//*****************************************************************************
//
// This function is called by the HTTP server whenever it encounters an SSI
// tag in a web page.  The iIndex parameter provides the index of the tag in
// the g_pcConfigSSITags array. This function writes the substitution text
// into the pcInsert array, writing no more than iInsertLen characters.
//
//*****************************************************************************
static int32_t
SSIHandler(int32_t iIndex, char *pcInsert, int32_t iInsertLen)
{
    //
    // Which SSI tag have we been passed?
    //
    switch(iIndex)
    {
        case SSI_INDEX_LEDSTATE:
            io_get_ledstate(pcInsert, iInsertLen);
            break;

        case SSI_INDEX_FORMVARS:
            usnprintf(pcInsert, iInsertLen,
                    "%sls=%d;\nsp=%d;\n%s",
                    JAVASCRIPT_HEADER,
                    io_is_led_on(),
                    io_get_animation_speed(),
                    JAVASCRIPT_FOOTER);
            break;

        case SSI_INDEX_SPEED:
            io_get_animation_speed_string(pcInsert, iInsertLen);
            break;

        default:
            usnprintf(pcInsert, iInsertLen, "??");
            break;
    }

    //
    // Tell the server how many characters our insert string contains.
    //
    return(strlen(pcInsert));
}

//*****************************************************************************
//
// The interrupt handler for the SysTick interrupt.
//
//*****************************************************************************
void
SysTickIntHandler(void)
{
    //
    // Call the lwIP timer handler.
    //
    lwIPTimer(SYSTICKMS);
    if(ipSetupRdy)
    {
		/* Increment counter for sensors */
		if( !(SystickCounter % ((SYSTICKHZ * WS_REFRESH_PERIOD_MS)/1000) ) )
		{
		tempInteger = IntegerPart(TempAmbientMeas);
		tempFraction = FractionPart(TempAmbientMeas);

		humidityInteger = IntegerPart(HumidityMeas);
		humidityFraction = FractionPart(HumidityMeas);

		pressureInteger = IntegerPart(PressureMeas);
		pressureFraction = FractionPart(PressureMeas);

		lightInteger = IntegerPart(LightMeas);
		lightFraction = FractionPart(LightMeas);

		UARTprintf("Temperature: %d.%d,  Humidity: %d.%d,  Pressure: %d.%d, Light: %d.%d\n ", tempInteger, tempFraction,
	    																					  humidityInteger, humidityFraction,
	    																					  pressureInteger, pressureFraction,
	    																					  lightInteger, lightFraction);
			/* Clear data ready flags */
			TempDataFlag = false;
			HumidityDataFlag = false;
			PressureDataFlag = false;
			LightDataFlag = false;
			SystickCounter = 0;
		}
		SystickCounter++;
    }
}

//*****************************************************************************
//
// The interrupt handler for the timer used to pace the animation.
//
//*****************************************************************************
void
AnimTimerIntHandler(void)
{
    //
    // Clear the timer interrupt.
    //
    MAP_TimerIntClear(TIMER2_BASE, TIMER_TIMA_TIMEOUT);

    //
    // Indicate that a timer interrupt has occurred.
    //
    HWREGBITW(&g_ulFlags, FLAG_TICK) = 1;
}

//*****************************************************************************
//
// Display an lwIP type IP Address.
//
//*****************************************************************************
void
DisplayIPAddress(uint32_t ui32Addr)
{
    char pcBuf[16];

    //
    // Convert the IP Address into a string.
    //
    usprintf(pcBuf, "%d.%d.%d.%d", ui32Addr & 0xff, (ui32Addr >> 8) & 0xff,
            (ui32Addr >> 16) & 0xff, (ui32Addr >> 24) & 0xff);

    //
    // Display the string.
    //
    UARTprintf(pcBuf);
}

//*****************************************************************************
//
// Required by lwIP library to support any host-related timer functions.
//
//*****************************************************************************
void
lwIPHostTimerHandler(void)
{
    uint32_t ui32NewIPAddress;

    //
    // Get the current IP address.
    //
    ui32NewIPAddress = lwIPLocalIPAddrGet();

    //
    // See if the IP address has changed.
    //
    if(ui32NewIPAddress != g_ui32IPAddress)
    {
        //
        // See if there is an IP address assigned.
        //
        if(ui32NewIPAddress == 0xffffffff)
        {
            //
            // Indicate that there is no link.
            //
            UARTprintf("Waiting for link.\n");
        }
        else if(ui32NewIPAddress == 0)
        {
            //
            // There is no IP address, so indicate that the DHCP process is
            // running.
            //
            UARTprintf("Waiting for IP address.\n");
        }
        else
        {
            //
            // Display the new IP address.
            //
            UARTprintf("IP Address: ");
            DisplayIPAddress(ui32NewIPAddress);
            UARTprintf("\n");
            UARTprintf("Open a browser and enter the IP address.\n");
            UARTprintf("Measurements will be sent periodically every %d milliseconds\n", WS_REFRESH_PERIOD_MS);
            ipSetupRdy = true;
        }

        //
        // Save the new IP address.
        //
        g_ui32IPAddress = ui32NewIPAddress;
    }

    //
    // If there is not an IP address.
    //
    if((ui32NewIPAddress == 0) || (ui32NewIPAddress == 0xffffffff))
    {
       //
       // Do nothing and keep waiting.
       //
    }
}

//*****************************************************************************
//
// This example demonstrates the use of the Ethernet Controller and lwIP
// TCP/IP stack to control various peripherals on the board via a web
// browser.
//
//*****************************************************************************
int
main(void)
{
    uint32_t ui32User0, ui32User1;
    uint8_t pui8MACArray[8];
    uint8_t LightMask;

    //
    // Make sure the main oscillator is enabled because this is required by
    // the PHY.  The system must have a 25MHz crystal attached to the OSC
    // pins.  The SYSCTL_MOSC_HIGHFREQ parameter is used when the crystal
    // frequency is 10MHz or higher.
    //
    SysCtlMOSCConfigSet(SYSCTL_MOSC_HIGHFREQ);

    //
    // Run from the PLL at 120 MHz.
    //
    g_ui32SysClock = MAP_SysCtlClockFreqSet((SYSCTL_XTAL_25MHZ |
                                             SYSCTL_OSC_MAIN |
                                             SYSCTL_USE_PLL |
                                             SYSCTL_CFG_VCO_480), 120000000);

    //
    // Configure the device pins.
    //
    PinoutSet(true, false);

    //
    // Configure debug port for internal use.
    //
    UARTStdioConfig(0, 115200, g_ui32SysClock);

    //
    // Clear the terminal and print a banner.
    //
    UARTprintf("Weather station serial test application\n");

    /* Enable the I2C7 peripheral before use. */
    ROM_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOD);
    ROM_SysCtlPeripheralEnable(SYSCTL_PERIPH_I2C7);

    /* Configure the pin muxing for I2C7 functions on port D0 and D1. */
    ROM_GPIOPinConfigure(GPIO_PD0_I2C7SCL);
    ROM_GPIOPinConfigure(GPIO_PD1_I2C7SDA);

    /* Select the I2C function for these pins.  This function will also configure the GPIO pins pins for I2C operation, setting them to
     * open-drain operation with weak pull-ups. */
    GPIOPinTypeI2CSCL(GPIO_PORTD_BASE, GPIO_PIN_0);
    ROM_GPIOPinTypeI2C(GPIO_PORTD_BASE, GPIO_PIN_1);

    /* Configure and Enable the GPIO interrupt. Used for DRDY from the TMP006 and for INT signal from the ISL29023*/
    ROM_GPIOPinTypeGPIOInput(GPIO_PORTH_BASE, GPIO_PIN_2);
    ROM_GPIOPinTypeGPIOInput(GPIO_PORTE_BASE, GPIO_PIN_5);
    GPIOIntEnable(GPIO_PORTH_BASE, GPIO_PIN_2);
    GPIOIntEnable(GPIO_PORTE_BASE, GPIO_PIN_5);
    ROM_GPIOIntTypeSet(GPIO_PORTH_BASE, GPIO_PIN_2, GPIO_FALLING_EDGE);
    ROM_GPIOIntTypeSet(GPIO_PORTE_BASE, GPIO_PIN_5, GPIO_FALLING_EDGE);
    ROM_IntEnable(INT_GPIOH);
    ROM_IntEnable(INT_GPIOE);

    /* Enable interrupts to the processor. */
    ROM_IntMasterEnable();

    /* Initialize I2C peripheral. */
    I2CMInit(&I2Cinstance, I2C7_BASE, INT_I2C7, 0xff, 0xff, g_ui32SysClock);

    /****************************************************************************************************************************************/
    /* Initialize the TMP006 */
    I2COperationInProgress = true;
    TMP006Init(&TempInst, &I2Cinstance, TMP006_I2C_ADDRESS,
                   DefaultAppCallback, &TempInst);

    /* Put the processor to sleep while we wait for the I2C driver to indicate that the transaction is complete. */
    I2CAppWait(__FILE__, __LINE__, WS_TemperatureSensor);

    /* clear the data flag for next use. */
    TempDataFlag = 0;

        /* Enable the DRDY pin indication that a conversion is in progress. */
    I2COperationInProgress = true;
    TMP006ReadModifyWrite(&TempInst, TMP006_O_CONFIG,
    		~TMP006_CONFIG_EN_DRDY_PIN_M,
			TMP006_CONFIG_EN_DRDY_PIN, DefaultAppCallback,
			&TempInst);
    /* Wait for the DRDY enable I2C transaction to complete. */
    I2CAppWait(__FILE__, __LINE__, WS_TemperatureSensor);
    /* Delay for 10 milliseconds for TMP006 reset to complete. Not explicitly required. Datasheet does not say how long a reset takes. */
    ROM_SysCtlDelay(g_ui32SysClock / (100 * 3));
    /* clear the data flag for next use. */
    TempDataFlag = 0;
    /****************************************************************************************************************************************/


        /****************************************************************************************************************************************/
    /* Initialize the SHT21. */
    I2COperationInProgress = true;
    SHT21Init(&HumidityInst, &I2Cinstance, SHT21_I2C_ADDRESS,
    		DefaultAppCallback, &HumidityInst);

    /* Wait for the I2C transactions to complete before moving forward. */
    I2CAppWait(__FILE__, __LINE__, WS_HumiditySensor);

    /*  Delay for 20 milliseconds for SHT21 reset to complete itself. */
    ROM_SysCtlDelay(g_ui32SysClock / (50 * 3));
    /****************************************************************************************************************************************/

    /****************************************************************************************************************************************/
    /* Initialize the BMP180. */
    I2COperationInProgress = true;
    BMP180Init(&PressureInst, &I2Cinstance, BMP180_I2C_ADDRESS,
        		DefaultAppCallback, &PressureInst);
        /* Wait for the I2C transactions to complete before moving forward. */
    I2CAppWait(__FILE__, __LINE__, WS_PressureSensor);
    PressureDataFlag = 0;

    /****************************************************************************************************************************************/

    /****************************************************************************************************************************************/
    /* Initialize ISL29023 */
    I2COperationInProgress = true;
    ISL29023Init(&LightInst, &I2Cinstance, ISL29023_I2C_ADDRESS,
                 DefaultAppCallback, &LightInst);
    /* Wait for transaction to complete */
    I2CAppWait(__FILE__, __LINE__, WS_LightSensor);

    /* Configure the ISL29023 to measure ambient light continuously. Set a 8 sample persistence before the INT pin is asserted. Clears the
     * INT flag. Persistence setting of 8 is sufficient to ignore camera flashes. */
    LightMask = (ISL29023_CMD_I_OP_MODE_M | ISL29023_CMD_I_INT_PERSIST_M |
                 ISL29023_CMD_I_INT_FLAG_M);
    I2COperationInProgress = true;
    ISL29023ReadModifyWrite(&LightInst, ISL29023_O_CMD_I, ~LightMask,
                           (ISL29023_CMD_I_OP_MODE_ALS_CONT |
                            ISL29023_CMD_I_INT_PERSIST_8),
                            DefaultAppCallback, &LightInst);

   /* Wait for transaction to complete */
   I2CAppWait(__FILE__, __LINE__, WS_LightSensor);

   /* Configure the upper threshold to 80% of maximum value */
   LightInst.pui8Data[1] = 0xCC;
   LightInst.pui8Data[2] = 0xCC;
   I2COperationInProgress = true;
   ISL29023Write(&LightInst, ISL29023_O_INT_HT_LSB,
                 LightInst.pui8Data, 2, DefaultAppCallback,
                 &LightInst);
   /* Wait for transaction to complete */
   I2CAppWait(__FILE__, __LINE__, WS_LightSensor);

       /* Configure the lower threshold to 20% of maximum value */
       LightInst.pui8Data[1] = 0x33;
       LightInst.pui8Data[2] = 0x33;
       I2COperationInProgress = true;
       ISL29023Write(&LightInst, ISL29023_O_INT_LT_LSB,
                     LightInst.pui8Data, 2, DefaultAppCallback,
                     &LightInst);
       /* Wait for transaction to complete */
    I2CAppWait(__FILE__, __LINE__, WS_LightSensor);

    //
    // Configure SysTick for a periodic interrupt.
    //
    ipSetupRdy = false;
    MAP_SysTickPeriodSet(g_ui32SysClock / SYSTICKHZ);
    MAP_SysTickEnable();
    MAP_SysTickIntEnable();

    //
    // Configure the hardware MAC address for Ethernet Controller filtering of
    // incoming packets.  The MAC address will be stored in the non-volatile
    // USER0 and USER1 registers.
    //
    MAP_FlashUserGet(&ui32User0, &ui32User1);
    if((ui32User0 == 0xffffffff) || (ui32User1 == 0xffffffff))
    {
        //
        // Let the user know there is no MAC address
        //
        UARTprintf("No MAC programmed!\n");

        while(1)
        {
        }
    }

    //
    // Tell the user what we are doing just now.
    //
    UARTprintf("Waiting for IP.\n");

    //
    // Convert the 24/24 split MAC address from NV ram into a 32/16 split
    // MAC address needed to program the hardware registers, then program
    // the MAC address into the Ethernet Controller registers.
    //
    pui8MACArray[0] = ((ui32User0 >>  0) & 0xff);
    pui8MACArray[1] = ((ui32User0 >>  8) & 0xff);
    pui8MACArray[2] = ((ui32User0 >> 16) & 0xff);
    pui8MACArray[3] = ((ui32User1 >>  0) & 0xff);
    pui8MACArray[4] = ((ui32User1 >>  8) & 0xff);
    pui8MACArray[5] = ((ui32User1 >> 16) & 0xff);

    //
    // Initialze the lwIP library, using DHCP.
    //
    lwIPInit(g_ui32SysClock, pui8MACArray, 0, 0, 0, IPADDR_USE_DHCP);

    //
    // Setup the device locator service.
    //
    LocatorInit();
    LocatorMACAddrSet(pui8MACArray);
    LocatorAppTitleSet("EK-TM4C1294XL enet_io");

    //
    // Initialize a sample httpd server.
    //
    httpd_init();

    //
    // Set the interrupt priorities.  We set the SysTick interrupt to a higher
    // priority than the Ethernet interrupt to ensure that the file system
    // tick is processed if SysTick occurs while the Ethernet handler is being
    // processed.  This is very likely since all the TCP/IP and HTTP work is
    // done in the context of the Ethernet interrupt.
    //
    MAP_IntPrioritySet(INT_EMAC0, ETHERNET_INT_PRIORITY);
    MAP_IntPrioritySet(FAULT_SYSTICK, SYSTICK_INT_PRIORITY);

    //
    // Pass our tag information to the HTTP server.
    //
    http_set_ssi_handler((tSSIHandler)SSIHandler, g_pcConfigSSITags,
            NUM_CONFIG_SSI_TAGS);

    //
    // Pass our CGI handlers to the HTTP server.
    //
    http_set_cgi_handlers(g_psConfigCGIURIs, NUM_CONFIG_CGI_URIS);

    //
    // Initialize IO controls
    //
    io_init();
    //
    // Loop forever, processing the on-screen animation.  All other work is
    // done in the interrupt handlers.
    //
    while(1)
    {
//        while(!g_ulFlags)
//        {
//            //
//            // Do nothing.
//            //
//        }


        /* Run until every measurement data is ready */
        if( (TempDataFlag == 0) || (HumidityDataFlag == 0) ||
            		(PressureDataFlag == 0) || (LightDataFlag == 0) )
        {
        	/* TMP006 sensor */
        	if( (TempDataFlag == false) && (TempStatus == 0) && (TempMeasReady == true))
        	{
        		I2COperationInProgress = true;
        		TMP006DataRead(&TempInst, TemperatureAppCallback, &TempInst);
        		I2CAppWait(__FILE__, __LINE__, WS_TemperatureSensor);
        		TMP006DataTemperatureGetFloat(&TempInst, &TempAmbientMeas, &TempObjectMeas);
        	}

        	/* SHT21 sensor */
        	if( (HumidityDataFlag == false) && (HumidityStatus == 0) )
        	{
        		/* Write the command to start measurement */
        		I2COperationInProgress = true;
        		SHT21Write(&HumidityInst, SHT21_CMD_MEAS_RH, HumidityInst.pui8Data, 0,
        				DefaultAppCallback, &HumidityInst);
        		/* Wait until command is sent */
        		I2CAppWait(__FILE__, __LINE__, WS_TemperatureSensor);

        		/* Wait 33 milliseconds before attempting to get the result. */
        		ROM_SysCtlDelay(g_ui32SysClock / (30 * 3));

                /* Get the raw data from the sensor over the I2C bus. */
                I2COperationInProgress = true;
                SHT21DataRead(&HumidityInst, HumidityAppCallback, &HumidityInst);
                /*Wait for the I2C transactions to complete before moving forward. */
                I2CAppWait(__FILE__, __LINE__, WS_HumiditySensor);

                /* Get a copy of the most recent raw data in floating point format. */
                SHT21DataHumidityGetFloat(&HumidityInst, &HumidityMeas);
            }

          	/* BMP180 sensor */
          	if( (PressureDataFlag == false) && (PressureStatus == 0) )
           	{

          		/* Start a read of data from the pressure sensor. */
          		I2COperationInProgress = true;
          		BMP180DataRead(&PressureInst, PressureAppCallback, &PressureInst);

          		/* Wait until command is sent */
          		I2CAppWait(__FILE__, __LINE__, WS_PressureSensor);

          		/* Get local copy of pressure data in float format */
          		BMP180DataPressureGetFloat(&PressureInst, &PressureMeas);
           	}

            /*ISL29023 sensor */
            if( (LightDataFlag == false) && (LightStatus == 0) )
            {
            	/* Intensity threshold changed, adjust range */
                if(LightIntensityFlag)
                {
                	LightAppAdjustRange(&LightInst);
                	LightIntensityFlag = false;
                }
                /* Start a read of data from the pressure sensor. */
                I2COperationInProgress = true;
                ISL29023DataRead(&LightInst, LightAppCallback, &LightInst);
                /* Wait until command is sent */
                I2CAppWait(__FILE__, __LINE__, WS_LightSensor);
                /* Get local copy of light data in float format */
                ISL29023DataLightVisibleGetFloat(&LightInst, &LightMeas);
            }
        }
        else
        {
        	MAP_SysCtlSleep();
        }


//        //
//        // Clear the flag now that we have seen it.
//        //
//        HWREGBITW(&g_ulFlags, FLAG_TICK) = 0;
//
//        //
//        // Toggle the GPIO
//        //
//        MAP_GPIOPinWrite(GPIO_PORTN_BASE, GPIO_PIN_1,
//                (MAP_GPIOPinRead(GPIO_PORTN_BASE, GPIO_PIN_1) ^
//                 GPIO_PIN_1));
    }
}
